#!/bin/bash

#chmod -R u+rx build	# I don't know why I have to do this now, but I do
rm -rf \
    build \
    dist \
    derivdelay.egg-info \
    __pycache__ */__pycache__ */*/__pycache__ \
    *.pyc */*.pyc */*/*.pyc */*/*/*.pyc */*/*/*/*.pyc

pipresult="True"

while [ -n "$pipresult" ]
do
    pipresult=`pip uninstall -y derivdelay | grep "Found existing"`
    if [[ -z $pipresult ]]
    then
        echo No installations found - quitting.
        break
    else
        echo "$pipresult" - removing.
    fi
done
