#!/bin/bash

# Checkout current state
git pull

# remove any previously installed versions
cleandirs

# install the package
#pip install -e .
pip install .

# remove the build directory
rm -rf derivdelay.egg-info build
